### 1. Создание новой задачи
POST http://localhost:8888/api/tasks
Content-Type: application/json

{
  "title": "Изучить бэкенд до косточек",
  "description": "Разобраться с архитектурой слоев, DTO и HTTP-статусами"
}

###

### 2. Получение списка всех задач
GET http://localhost:8888/api/tasks


### 3. Краш-тест: Пустой title (Ожидаем 400 Bad Request)
POST http://localhost:8888/api/tasks
Content-Type: application/json

{
  "title": "   ",
  "description": "Тут нормальное описание, но заголовок состоит из пробелов"
}

###

### 4. Краш-тест: Слишком длинное описание (Ожидаем 400 Bad Request)
POST http://localhost:8888/api/tasks
Content-Type: application/json

{
  "title": "Валидный заголовок",
  "description": "Этот текст специально сделан огромным, чтобы пробить лимит в пятьсот символов. Этот текст специально сделан огромным, чтобы пробить лимит в пятьсот символов. Этот текст специально сделан огромным, чтобы пробить лимит в пятьсот символов. Этот текст специально сделан огромным, чтобы пробить лимит в пятьсот символов. Этот текст специально сделан огромным, чтобы пробить лимит в пятьсот символов. Этот текст специально сделан огромным, чтобы пробить лимит в пятьсот символов. Этот текст специально сделан огромным, чтобы пробить лимит в пятьсот символов."
}

### 5
GET http://localhost:8888/api/tasks/9999

### 6. Создание задачи (с привязкой к юзеру)
POST http://localhost:8888/api/tasks
Content-Type: application/json

{
  "title": "Изучить связи в JPA",
  "description": "Разделение на ManyToOne и OneToMany",
  "userId": 1
}

### 7. Создание нового пользователя
POST http://localhost:8888/api/users
Content-Type: application/json

{
  "username": "damir",
  "email": "damir@example.com"
}

### 8. Получение всех пользователей
GET http://localhost:8888/api/users

### Получить все задачи Дамира (у которого id = 1)
GET http://localhost:8888/api/users/1/tasks

### Попытка получить задачи фантомного юзера (вернет красивую 404)
GET http://localhost:8888/api/users/9999/tasks