### 1. Создание новой задачи
POST http://localhost:8888/api/tasks
Content-Type: application/json

{
  "title": "Изучить бэкенд до косточек",
  "description": "Разобраться с архитектурой слоев, DTO и HTTP-статусами"
}

###

### 2. Получение списка всех задач
GET http://localhost:8888/api/tasks


### 3. Краш-тест: Пустой title (Ожидаем 400 Bad Request)
POST http://localhost:8888/api/tasks
Content-Type: application/json

{
  "title": "   ",
  "description": "Тут нормальное описание, но заголовок состоит из пробелов"
}

###

### 4. Краш-тест: Слишком длинное описание (Ожидаем 400 Bad Request)
POST http://localhost:8888/api/tasks
Content-Type: application/json

{
  "title": "Валидный заголовок",
  "description": "Этот текст специально сделан огромным, чтобы пробить лимит в пятьсот символов. Этот текст специально сделан огромным, чтобы пробить лимит в пятьсот символов. Этот текст специально сделан огромным, чтобы пробить лимит в пятьсот символов. Этот текст специально сделан огромным, чтобы пробить лимит в пятьсот символов. Этот текст специально сделан огромным, чтобы пробить лимит в пятьсот символов. Этот текст специально сделан огромным, чтобы пробить лимит в пятьсот символов. Этот текст специально сделан огромным, чтобы пробить лимит в пятьсот символов."
}